### ISSUE TITLE
what benefit in separating this from patchwork?

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork-ui#409]
what is the advantage that this is a separate repo to patchwork?
I can't see clear benefit from it being separated (although patchwork-api is different)
and this does make it a little harder to keep up to date correctly.

**Comment by pfraze** [comment]
No major benefit. Should we merge them?

**Comment by dominictarr** [comment]
I think that might make versions easier to manage

**Comment by pfraze** [comment]
Yeah. It's much easier to tell people to update patchwork than a pw dep

**Comment by pfraze** [comment]
merged
